# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/ES31_S26/Final_Project/fixing_warnings/ENGS31FINAL-main/VHDL/engs31_final_warning_fix/engs31_final_warning_fix.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ES31_S26/Final_Project/fixing_warnings/ENGS31FINAL-main/VHDL/engs31_final_warning_fix/engs31_final_warning_fix.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: o:/ES31_S26/Final_Project/fixing_warnings/ENGS31FINAL-main/VHDL/engs31_final_warning_fix/engs31_final_warning_fix.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ES31_S26/Final_Project/fixing_warnings/ENGS31FINAL-main/VHDL/engs31_final_warning_fix/engs31_final_warning_fix.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
